services:
  frontend:
    image: neptade/mlprod_frontend:latest
    ports:
      - "3000:3000"

  backend:
    image: neptade/mlprod_backend:latest
    ports:
      - "5005:5005"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
