name: Pull Request to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  pr_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install python dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        working-directory: ./backend
        run: python3 apptest.py
          
