name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the backend Docker image
      run: docker build ./backend -t alange20/e2e_backend:latest 

    - name: Push the backend Docker image to Docker Hub
      run: docker push alange20/e2e_backend:latest

    - name: Build the frontend the Docker image
      run: docker build ./frontend -t alange20/e2e_frontend:latest

    - name: Push the frontend Docker image to Docker Hub
      run: docker push alange20/e2e_frontend:latest

      