name: Push to Main from Staging

on:
  push:
    branches:
      - staging

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run unit tests
        working-directory: ./frontend
        run: npm run test

      - name: Install python dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run integration tests
        working-directory: ./backend
        run: python3 apptest.py

      - name: Install e2e dependencies
        working-directory: ./e2e
        run: npm install

      - name: Start Frontend
        working-directory: ./frontend
        run: npm start&

      - name: Run 2e2 tests
        working-directory: ./e2e
        run: | 
          npx playwright install
          npx playwright test e2e.test.js


      #

  auto_merge_to_main:
      needs: build_and_test
      runs-on: ubuntu-latest
      if: success()

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Merge Dev to Main
          uses: devmasx/merge-branch@master
          with:
            type: now
            from_branch: staging
            target_branch: main
            github_token: ${{ secrets.USER_TOKEN }}
